export const ACTION_TYPES = {
  CLEAR_STATUS: "CLEAR_STATUS",
  EMPTY_QUERY: "EMPTY_QUERY",
  INVALID_QUERY: "INVALID_QUERY",
  FETCH_START: "FETCH_START",
  FETCH_SUCCESS: "FETCH_SUCCESS",
  FETCH_ERROR: "FETCH_ERROR",
  ADD_PHONETIC: "ADD_PHONETIC",
  ADD_AUDIO: "ADD_AUDIO",
};
